export default function Home() {
  return (
    <div className="shell">
      <nav><a className="brand" href="#top">TÓPODA <i>CHARTS</i></a><div className="navlinks"><a href="#universe">Universe</a><a href="#rls">RLS</a><a href="#tth">TTH</a><a href="#gaia">Gaia</a></div><div className="status">Music · Power · Legacy</div></nav>
      <main>
        <section id="top" className="hero">
          <div className="hero-copy"><p className="kicker">Tópoda Charts presents</p><h1>Every record<span>leaves a legacy.</span></h1><p className="intro">Enter a shared universe where music moves markets, creates icons, destroys relationships, and writes history. Build its future in <strong>Record Label Simulator</strong>. Discover the lives that came before in <strong>The Twenty-four Hundreds</strong>.</p><div className="actions"><a className="btn primary" href="/rls">Play RLS <b>↗</b></a><a className="btn" href="/tth">Enter the story <b>→</b></a></div></div>
          <aside className="layer-map"><div className="map-head">Choose your way into Gaia</div><div className="layer"><b>PLAY</b><div><h2>RLS</h2><p>Find the next voice. Build the label. Fight for the top.</p></div></div><div className="layer"><b>READ</b><div><h2>TTH</h2><p>One invitation. One final night. A century about to turn.</p></div></div><div className="layer"><b>ENTER</b><div><h2>Gaia</h2><p>A future Earth where songs cross borders—and ambition redraws them.</p></div></div></aside>
        </section>
        <div className="ticker"><div>SIGN THE ACT&nbsp;&nbsp;◆&nbsp;&nbsp;SHAPE THE ERA&nbsp;&nbsp;◆&nbsp;&nbsp;MOVE THE CHARTS&nbsp;&nbsp;◆&nbsp;&nbsp;LEAVE A LEGACY&nbsp;&nbsp;◆&nbsp;&nbsp;SIGN THE ACT&nbsp;&nbsp;◆&nbsp;&nbsp;SHAPE THE ERA&nbsp;&nbsp;◆&nbsp;&nbsp;MOVE THE CHARTS&nbsp;&nbsp;◆&nbsp;&nbsp;LEAVE A LEGACY&nbsp;&nbsp;◆&nbsp;&nbsp;</div></div>
        <section id="universe" className="section"><div className="section-head"><div><p className="section-label">The Tópoda Charts Universe</p><h2>One world. Every consequence.</h2></div><p className="section-lede">A song born in a bedroom can ignite a country. A stranger can become the face of a generation. A rivalry can outlive everyone who started it. Across the game and the stories, the same artists, cities, scandals, and songs keep colliding—turning private choices into the history of Gaia.</p></div><div className="system-grid universe-grid"><article className="system"><small>THE SOUND</small><h3>A song can change everything</h3><p>One undeniable record can cross borders, revive a career, or put an unknown name on every screen in Gaia.</p></article><article className="system"><small>THE STARS</small><h3>Icons are made in public</h3><p>Talent earns attention. Charisma builds devotion. Pressure reveals who can survive being seen by everyone.</p></article><article className="system"><small>THE RIVALRIES</small><h3>Success creates enemies</h3><p>Competing labels, wounded friends, hungry newcomers, and old betrayals make every victory personal.</p></article><article className="system"><small>THE AFTERMATH</small><h3>Fame leaves a shadow</h3><p>The charts move on. People remember. Every triumph, collapse, and comeback becomes part of the next story.</p></article></div></section>
        <section id="rls" className="section rls"><div className="section-head"><div><p className="section-label">01 / The game</p><h2>Record Label Simulator</h2></div><p className="section-lede">Start with an empty office and an ear for the future. Discover voices before the world knows their names, gamble on the records you believe in, and build a label powerful enough to define an era. Every artist has ambitions. Every audience is unpredictable. Every number-one has somebody coming for it.</p></div><div className="system-grid"><article className="system"><small>DISCOVER</small><h3>Hear tomorrow first</h3><p>Find raw talent in overlooked scenes and decide who deserves the chance that could change both your lives.</p></article><article className="system"><small>CREATE</small><h3>Turn promise into a phenomenon</h3><p>Choose the sound, image, collaborators, and moment that can transform a great song into a cultural event.</p></article><article className="system"><small>COMPETE</small><h3>Fight for every listener</h3><p>Outmaneuver rival labels, survive bad press, and keep the world watching when the next sensation arrives.</p></article><article className="system"><small>ENDURE</small><h3>Become more than a hit</h3><p>Manage egos, expectations, and reinvention. Build careers that survive the charts—and a legacy that outlives you.</p></article></div><div className="pipeline"><b>Find the voice</b><span className="arrow">→</span><b>Make the record</b><span className="arrow">→</span><b>Capture the world</b><span className="arrow">→</span><b>Defend the crown</b></div><div className="actions"><a className="btn primary" href="/rls">Build your label <b>↗</b></a></div></section>
        <div className="split"><section id="tth" className="feature"><span className="num">02 / THE STORY</span><h2>The Twenty-four Hundreds</h2><p>December 31, 2399. The century has hours left. Marc Hann receives an invitation he was never meant to need—and walks into a night of old wounds, shifting loyalties, and friendships one secret away from breaking. Before they became legends, they were young, reckless, and desperate to matter.</p><a className="fact" href="/tth">Enter the final night →</a></section><section id="gaia" className="feature gaia"><span className="num">03 / THE WORLD</span><h2>Welcome to Gaia.</h2><p>Future Earth survived catastrophe and became something new. In Annglora, Bytenza, and Crowlya, music travels faster than politics, stars become symbols, and the next cultural revolution may begin with one voice nobody can ignore.</p><span className="fact">Three nations. One global stage.</span></section></div>
        <section className="origin"><div><h2>Hear the hit. Know the story.</h2></div><div><p>Play the rise of the label. Read the lives behind the legends. Cross the borders of Gaia and watch a song become a movement, a romance become a scandal, and a single night echo across an entire century.</p></div></section>
      </main>
      <footer><a className="footer-brand brand" href="#top">TÓPODA <i>CHARTS</i></a><span>Record Label Simulator</span><span>The Twenty-four Hundreds · Gaia</span></footer>
    </div>
  );
}
