export default function Home() {
  return (
    <div className="shell">
      <nav><a className="brand" href="#top">TÓPODA <i>CHARTS</i></a><div className="navlinks"><a href="#universe">Universe</a><a href="#rls">RLS</a><a href="#tth">TTH</a><a href="#gaia">Gaia</a></div><div className="status">A living music universe</div></nav>
      <main>
        <section id="top" className="hero">
          <div className="hero-copy"><p className="kicker">Tópoda Charts presents</p><h1>Every record<span>leaves a legacy.</span></h1><p className="intro">Enter a shared universe where music moves markets, creates icons, destroys relationships, and writes history. Build its future in <strong>Record Label Simulator</strong>. Discover the lives that came before in <strong>The Twenty-four Hundreds</strong>.</p><div className="actions"><a className="btn primary" href="/rls">Play RLS <b>↗</b></a><a className="btn" href="/tth">Enter the story <b>→</b></a></div></div>
          <aside className="layer-map"><div className="map-head">One universe / three ways in</div><div className="layer"><b>01</b><div><h2>RLS</h2><p>Run the label. Shape the sound. Command the charts.</p></div></div><div className="layer"><b>02</b><div><h2>TTH</h2><p>Live the years before the game—and the people who made them matter.</p></div></div><div className="layer"><b>03</b><div><h2>Gaia</h2><p>One future Earth. Every career, country, rivalry, and consequence.</p></div></div></aside>
        </section>
        <div className="ticker"><div>SIGN THE ACT&nbsp;&nbsp;◆&nbsp;&nbsp;SHAPE THE ERA&nbsp;&nbsp;◆&nbsp;&nbsp;MOVE THE CHARTS&nbsp;&nbsp;◆&nbsp;&nbsp;LEAVE A LEGACY&nbsp;&nbsp;◆&nbsp;&nbsp;SIGN THE ACT&nbsp;&nbsp;◆&nbsp;&nbsp;SHAPE THE ERA&nbsp;&nbsp;◆&nbsp;&nbsp;MOVE THE CHARTS&nbsp;&nbsp;◆&nbsp;&nbsp;LEAVE A LEGACY&nbsp;&nbsp;◆&nbsp;&nbsp;</div></div>
        <section id="universe" className="section"><div className="section-head"><div><p className="section-label">The shared universe</p><h2>One world. Every consequence.</h2></div><p className="section-lede">A chart position is never just a number. Behind it is an Act, a record label, an audience, a country, a relationship, and a moment in history. Record Label Simulator and The Twenty-four Hundreds share the same people, places, music, and memory—what happens in one gives meaning to the other.</p></div><div className="system-grid universe-grid"><article className="system"><small>THE INDUSTRY</small><h3>Music makes history</h3><p>Careers become eras. Releases become cultural events. Labels rise by understanding the world around them.</p></article><article className="system"><small>THE PEOPLE</small><h3>Legends begin somewhere</h3><p>Every icon has a private life, every rivalry has a first wound, and every public story leaves something out.</p></article><article className="system"><small>THE WORLD</small><h3>Gaia remembers</h3><p>Nations, languages, markets, and audiences carry centuries of history into every song they embrace or reject.</p></article><article className="system"><small>THE LEGACY</small><h3>Nothing disappears</h3><p>The past becomes context. Context becomes pressure. Pressure becomes the next decision.</p></article></div></section>
        <section id="rls" className="section rls"><div className="section-head"><div><p className="section-label">01 / Flagship game</p><h2>Record Label Simulator</h2></div><p className="section-lede">Run a label inside a living music market. Find talent, shape Acts, turn raw material into releases, spend where it matters, compete for attention, and watch every decision change a career. Your triumphs—and your disasters—always have a history.</p></div><div className="system-grid"><article className="system"><small>YOUR ROSTER</small><h3>Build the names people remember</h3><p>Sign the Creators who make the music. Build the Acts the public will love, hate, follow, and never stop talking about.</p></article><article className="system"><small>YOUR RELEASES</small><h3>Take an idea to the world</h3><p>Move music through writing, recording, production, staging, and release. Every shortcut costs something.</p></article><article className="system"><small>YOUR MARKET</small><h3>Win the moment</h3><p>Read audiences, choose the right promotion, face critics and rivals, and turn attention into chart power.</p></article><article className="system"><small>YOUR LEGACY</small><h3>Own the era</h3><p>A hit can save a quarter. An era can define a career. A Legacy decides what the world remembers.</p></article></div><div className="pipeline"><b>Sheet Music</b><span className="arrow">→</span><b>Demo Recording</b><span className="arrow">→</span><b>Master</b><span className="arrow">→</span><b>Track / Project</b></div><div className="actions"><a className="btn primary" href="/rls">Play Record Label Simulator <b>↗</b></a></div></section>
        <div className="split"><section id="tth" className="feature"><span className="num">02 / EPISODIC PROSE</span><h2>The Twenty-four Hundreds</h2><p>December 31, 2399. Marc Hann enters the final night of the century carrying a social wound and a last-minute invitation. Before the labels, charts, and legends of RLS, there were people trying to survive each other—and become unforgettable.</p><a className="fact" href="/tth">Enter the final night →</a></section><section id="gaia" className="feature gaia"><span className="num">03 / THE SHARED WORLD</span><h2>Earth became Gaia.</h2><p>Centuries after catastrophe reshaped civilization, future Earth has new nations, new power, and new ways to be heard. Annglora, Bytenza, and Crowlya meet through culture—and collide through ambition.</p><span className="fact">One planet. A new age.</span></section></div>
        <section className="origin"><div><h2>The universe remembers.</h2></div><div><p>A forgotten demo. A first betrayal. A country discovering a new sound. A label betting everything on one Act. In Gaia, every private choice can become public history—and every era leaves something for the next one to inherit.</p></div></section>
      </main>
      <footer><a className="footer-brand brand" href="#top">TÓPODA <i>CHARTS</i></a><span>Record Label Simulator</span><span>The Twenty-four Hundreds · Gaia</span></footer>
    </div>
  );
}
